### ISSUE TITLE
Object detection

### ISSUE THREAD

**Issue by DrVijayK** [MINZHIJI/nvdla_exploration#1]
@MINZHIJI 
You have done an amazing and very impressive work. Just wanted to check with you on whether you were able to successfully perform object detection with NVDLA with any network. If so, it will be of great help if you can point to such prototxt and caffemodel.

**Comment by MINZHIJI** [comment]
Thanks. 
I don't have any executable object detection sample, sorry.
And I opened the issue on NVDLA project -- https://github.com/nvdla/sw/issues/63, but currently without any answer.
If any question, welcome to reopen issue.

The NVDLA exploration work is temporarily suspended.  Because I am preparing my master's thesis.
